# Generated by Django 2.2.12 on 2023-02-20 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('contactno', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('address', models.CharField(default='', max_length=200)),
                ('space', models.CharField(default='', max_length=30)),
                ('message', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mail', models.CharField(default='null', max_length=200)),
                ('contactno', models.CharField(default='', max_length=10)),
                ('question', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('mes_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('passwordr', models.CharField(default='', max_length=20)),
                ('addressfor', models.CharField(default='', max_length=200)),
                ('contactnumber', models.CharField(default='', max_length=10)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10)),
                ('ques', models.CharField(choices=[('book', 'What Is your favorite book?'), ('food', 'What is your favorite food?'), ('city', 'What city were you born in?'), ('place', 'Where is your favorite place to vacation?')], default='book', max_length=10)),
                ('answer', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicleentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnumber', models.CharField(max_length=10)),
                ('vtype', models.CharField(choices=[('two', 'Two Wheeler'), ('three', 'Three Wheeler'), ('four', 'Four Wheeler')], default='two', max_length=10)),
                ('contactno', models.CharField(default='', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('intime', models.TimeField(blank=True, null=True)),
                ('spacealloted', models.CharField(max_length=10)),
                ('flooralloted', models.CharField(max_length=10)),
                ('tagno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicleexit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vno', models.CharField(default='', max_length=10)),
                ('vty', models.CharField(choices=[('two', 'Two Wheeler'), ('three', 'Three Wheeler'), ('four', 'Four Wheeler')], default='two', max_length=10)),
                ('outtime', models.TimeField(blank=True, null=True)),
                ('farem', models.CharField(blank=True, max_length=4, null=True)),
                ('tno', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
